version: '3.8'

volumes:
  postgres:

services:
  postgres:
    image: 'postgres:15.5-alpine3.17'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: glasskube
    volumes:
      - 'postgres:/var/lib/postgresql/types/'
    ports:
      - '5432:5432'
