name: cloud

services:
  postgres:
    image: 'postgres:17.2-alpine3.20'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: glasskube
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'
  mailpit:
    image: 'axllent/mailpit:v1.21.7'
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres:
