FROM golang:1.23 AS builder
ARG TARGETOS
ARG TARGETARCH
ARG VERSION
ARG COMMIT

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY api/ api/
COPY cmd/agent/kubernetes/ cmd/agent/kubernetes/
# doesn't exist (yet?)
# COPY pkg/ pkg/
COPY internal/ internal/
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH} \
  go build -a -o agent \
  -ldflags="-s -w -X github.com/glasskube/cloud/internal/buildconfig.version=${VERSION:-snapshot} -X github.com/glasskube/cloud/internal/buildconfig.commit=${COMMIT}" \
  ./cmd/agent/kubernetes/

FROM gcr.io/distroless/static-debian12:nonroot@sha256:6ec5aa99dc335666e79dc64e4a6c8b89c33a543a1967f20d360922a80dd21f02
WORKDIR /
COPY --from=builder /workspace/agent .

ENTRYPOINT ["/agent"]
