name: distr-dev

services:
  postgres:
    image: 'postgres:17.4-alpine3.20'
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: distr
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
    ports:
      - '5432:5432'
  mailpit:
    image: 'axllent/mailpit:v1.23.1'
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  postgres:
