name: distr

services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
    restart: always
    healthcheck:
      test: pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      start_interval: 1s
      interval: 5s
      retries: 6
  hub:
    image: ghcr.io/glasskube/distr:1.5.0 # x-release-please-version
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '8080:8080'
      - '8585:8585'
    restart: always

  # The OCI registry of distr can use any S3 compatible storage to store OCI images.
  # If you don't want to use the OCI registry (REGISTRY_ENABLED=false) or want to use an external S3 provider,
  # you don't need to run the minio service.
  minio:
    image: 'minio/minio:RELEASE.2025-02-28T09-55-16Z'
    entrypoint: sh
    command:
      - -c
      - mkdir -p /data/distr && minio server /data --console-address :9001
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio:/data/

volumes:
  postgres:
  minio:
