name: distr

services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - 'postgres:/var/lib/postgresql/data/'
    restart: always
    healthcheck:
      test: pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      start_interval: 1s
      interval: 5s
      retries: 6
  hub:
    image: ghcr.io/glasskube/distr:1.3.1 # x-release-please-version
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - '8080:8080'
    restart: always

volumes:
  postgres:
