name: glasskube-agent
services:
  agent:
    network_mode: host
    image: 'glasskube-agent' # TODO tag
    environment:
      GK_ACCESS_KEY_ID: '{{ .accessKeyId }}'
      GK_ACCESS_KEY_SECRET: '{{ .accessKeySecret }}'
      GK_RESOURCE_ENDPOINT: '{{ .resourcesEndpoint }}'
      GK_STATUS_ENDPOINT: '{{ .statusEndpoint }}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
