name: glasskube-agent
services:
  agent:
    network_mode: host
    image: 'glasskube-agent' # TODO tag
    environment:
      GK_TARGET_ID: '{{ .targetId }}'
      GK_TARGET_SECRET: '{{ .targetSecret }}'
      GK_RESOURCE_ENDPOINT: '{{ .resourcesEndpoint }}'
      GK_STATUS_ENDPOINT: '{{ .statusEndpoint }}'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
