{{- range $job := .Values.cronJobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "distr.fullname" $ }}-{{ $job.name }}
  labels:
    {{- include "distr.labels" $ | nindent 4 }}
    {{- with $job.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  concurrencyPolicy: {{ $job.concurrencyPolicy | default "Forbid" }}
  schedule: "{{ $job.schedule | default "0 * * * *" }}"
  jobTemplate:
    metadata:
      labels:
        {{- include "distr.labels" $ | nindent 8 }}
        {{- with $job.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      template:
        metadata:
          labels:
            {{- include "distr.labels" $ | nindent 12 }}
            {{- with $job.labels }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
        spec:
          containers:
            - name: hub
              {{- with $job.args }}
              args:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              {{- with $.Values.securityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
              imagePullPolicy: {{ $.Values.image.pullPolicy }}
              {{- with $.Values.hub.envFrom }}
              envFrom:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              env:
                {{- include "distr.hubEnv" $ | nindent 16 }}
          restartPolicy: {{ $job.restartPolicy | default "OnFailure" }}
{{- end }}
