name: shiori-distr-sample

services:
  shiori:
    image: 'ghcr.io/go-shiori/shiori:v1.7.4'
    ports:
      - '8081:8080'
    volumes:
      - 'shiori:/srv/shiori'
    restart: unless-stopped
    depends_on:
      - shiori-postgres
    environment:
      SHIORI_DIR: /srv/shiori
      SHIORI_DATABASE_URL: postgres://shiori:shiori@shiori-postgres/shiori?sslmode=disable

  shiori-postgres:
    image: 'postgres:17.2-alpine3.20'
    environment:
      POSTGRES_PASSWORD: shiori
      POSTGRES_USER: shiori
    ports:
      - '5433:5432'
    volumes:
      - 'shiori-postgres:/var/lib/postgresql/data/'

volumes:
  shiori-postgres:
  shiori:
