name: Build SDK

on:
  push:
    branches:
      - 'main'
    paths:
      - 'sdk/**'
      - 'tsconfig.json'
      - '.github/workflows/build-sdk.yaml'
    tags:
      - '*'
  pull_request:
    paths:
      - sdk/**
      - 'tsconfig.json'
      - .github/workflows/build-sdk.yaml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sdk/js
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          sparse-checkout: |
            sdk
            tsconfig.json
          sparse-checkout-cone-mode: false
      - name: Install pnpm
        uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0
        with:
          package_json_file: sdk/js/package.json

      - name: Setup node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: 'sdk/js/package.json'
          cache: pnpm
          cache-dependency-path: sdk/js/pnpm-lock.yaml
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build application
        run: pnpm run build
      - name: Build docs
        run: pnpm run docs
      - name: Check if repository is clean
        run: |
          STATUS="$(git status --porcelain)"
          if [ -z "$STATUS" ]; then
            echo Repository is clean.
          else
            echo "Repository is not clean:"
            git diff
            echo "You might want to run 'pnpm i && pnpm run docs' in sdk/js and try again"
            exit 1
          fi
      - name: Publish to npmjs
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: pnpm publish --access public --no-git-checks
