name: Build application and upload sourcemaps

on:
  push:
    tags:
      - '*'

jobs:
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install tools
        uses: jdx/mise-action@249c01ba271e19fa76eede7f766161cc95ace489 # v2.1.10
      - name: Install frontend dependencies with npm
        run: npm ci
      - name: Build application with source maps
        run: npm run build:prod -- --source-map=true
      - name: Generate Sentry Release
        run: npm run sentry-upload
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          VERSION: ${{ github.ref_name }}
