name: Build the application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install tools
        uses: jdx/mise-action@249c01ba271e19fa76eede7f766161cc95ace489 # v2.1.10
      - name: Install frontend dependencies with npm
        run: npm ci
      - name: Lint frontend
        run: npm run lint
      - name: Lint go project
        run: golangci-lint run --out-format=colored-line-number
      - name: Build application
        run: make build
