name: Build the application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Install tools
        uses: jdx/mise-action@5bb8f8c1911837cf42064e6490e7634fc842ee7e # v2.1.8
      - name: Install frontend dependencies with npm
        run: npm ci
      - name: Lint frontend
        run: npm run lint
      - name: Lint go project
        run: golangci-lint run --out-format=colored-line-number
      - name: Build application
        run: make build
